higgsr_lidar_client:
  ros__parameters:
    # === 라이다 설정 ===
    lidar_topic: "/ouster/points"                   # 구독할 라이다 포인트클라우드 토픽
    
    # === TF 및 프레임 설정 ===
    publish_tf: true                                # TF 변환 브로드캐스트 여부
    base_frame_id: "os_lidar"                      # 로봇 베이스 프레임 ID
    map_frame_id: "map"                      # 글로벌 맵 프레임 ID
    odom_frame_id: "odom"                           # 오도메트리 프레임 ID
    
    # === 퍼블리시 토픽 설정 ===
    pose_topic: "higgsr_pose"                       # 추정된 포즈 퍼블리시 토픽
    transform_topic: "higgsr_transform"             # 변환 행렬 퍼블리시 토픽
    
    # === 서비스 설정 ===
    registration_service: "register_scan"          # 스캔 정합 서비스 이름
    
    # === 처리 설정 ===
    registration_timeout: 30.0                     # 정합 서비스 타임아웃 (초)
    max_scan_age: 5.0                              # 최대 스캔 데이터 사용 시간 (초) 